tunnel: [redacted tunnel ID]
credentials-file: /home/ubuntu/.cloudflared/[redacted tunnel ID].json
ingress:
  - hostname: www.rootrecord.cloud
    service: http://127.0.0.1:8090
  - hostname: ssh.rootrecord.cloud
    service: ssh://localhost:22
  - service: http_status:404
